# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_edituser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeleteUser',
        ),
        migrations.DeleteModel(
            name='EditUser',
        ),
    ]
