# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='user_fk',
            field=models.ManyToManyField(to='users.UserProxy'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='course_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
