# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20160420_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddStudents',
        ),
    ]
