# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_fileupload'),
        ('courses', '0010_chapter_slug'),
    ]

    operations = [
    ]
