# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20160501_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
